// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lizmmpkfddkkjeohgxve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxpem1tcGtmZGRra2plb2hneHZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxODI0NjUsImV4cCI6MjA1OTc1ODQ2NX0.HA97FYI2Z0AFctzJRhN0ZslMxzyQufALRXI6pUQIOlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);